<?php

/**
 * @file
 * Provides a ninja stats entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function ninja_stats_theme() {
  return [
    'ninja_stats' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for ninja stats templates.
 *
 * Default template: ninja-stats.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the ninja stats information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_ninja_stats(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
